# Generated by Django 3.2 on 2023-03-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
    ]
