# Generated by Django 3.2 on 2023-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0004_auto_20230330_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denonciation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='denonciation_audios'),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='denonciation_files'),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='pictures',
            field=models.ImageField(upload_to='denonciations_images'),
        ),
    ]
