# Generated by Django 3.2 on 2023-03-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0005_auto_20230330_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='step',
            name='status',
        ),
    ]
