# Generated by Django 3.2 on 2023-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0006_auto_20230330_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denonciation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la denonciation'),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='denonciations_images'),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='denonciator',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='denonciator',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
