# Generated by Django 3.2 on 2023-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0007_auto_20230330_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='category',
            field=models.CharField(choices=[('VICTIME', 'VICTIM'), ('ACTEUR', 'ACTOR'), ('WITNESS', 'WITNESS')], default='WITNESS', max_length=200),
        ),
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.CharField(choices=[('INDIVIDU', 'INDIVIDU'), ('GROUPE', 'GROUP')], default='INDIVIDU', max_length=200),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='priority',
            field=models.CharField(choices=[('EN COURS', 'IN_PROGESS'), ('DEJA PASSEE', 'PASSED')], default='DEJA PASSEE', max_length=200),
        ),
        migrations.AlterField(
            model_name='denonciation',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'PENDING'), ('EN COURS', 'IN_PROGESS'), ('REJETTEE', 'REJECTED'), ('TERMINEE', 'COMPLETED')], default='EN ATTENTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('ACTUALITE', 'ACTUALITE'), ('DECRET', 'DECRET'), ('DROITS', 'DROITS'), ('RESOLUTION', 'RESOLUTION'), ('INFORMATION', 'INFORMATION')], default='ACTUALITE', max_length=200),
        ),
    ]
