# Generated by Django 3.2 on 2023-03-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denonciationapp', '0010_auto_20230331_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='denonciator',
            name='follow_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
