# Generated by Django 3.2 on 2023-03-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230331_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(null=True, verbose_name="Description de l'Equipe"),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='PINCIPAL', max_length=225, unique=True),
        ),
    ]
